batch_size: 32
beta: 1.0
binding_predictor_type: dummy
checkpoint_frequency: 4
delta: 1.0
device: cpu
glycan_encoder_type: dummy
glycan_type: SMILES
glycans_data_path: data/GlycanML/glycans.tsv
hf_auth: false
k_folds: 3
learning_rate: 0.001
log_predict: false
loss_type: rmsle
model_specific_params: {}
num_epochs: 4
output_dir: experiments
predict_data_path: data/GlycanML/train_fractions.tsv
protein_encoder_type: dummy
proteins_data_path: data/GlycanML/proteins.tsv
random_state: 42
split_mode: AND
train_final_model: false
use_kfold: false
val_split: 0.3
