batch_size: 32
beta: 1.0
binding_predictor_type: dummy
checkpoint_frequency: 3
delta: 1.0
device: cpu
glycan_encoder_type: dummy
glycan_type: SMILES
glycans_data_path: data/Glycan-Structures-CFG611.txt
hf_auth: false
k_folds: 3
learning_rate: 0.005
log_predict: true
loss_type: mse
model_specific_params: {}
num_epochs: 10
output_dir: experiments
predict_data_path: data/Train_Fractions.csv
protein_encoder_type: dummy
proteins_data_path: data/Protein-Sequence-Table.txt
random_state: 42
split_mode: AND
train_final_model: false
use_kfold: false
val_split: 0.5
