# required
output_dir: "experiments"
predict_data_path: "data/Fractions-Bound-Table.txt"
glycans_data_path: "data/Glycan-Structures-CFG611.txt"
proteins_data_path: "data/Protein-Sequence-Table.txt"
glycan_encoder_type: "dummy"
protein_encoder_type: "dummy"
binding_predictor_type: "dummy"
num_epochs: 10
batch_size: 32
learning_rate: 0.001
checkpoint_frequency: 2

# optional
val_split: 0.2
device: "cpu"
model_specific_params: {}
hf_auth: False