# required
output_dir: "experiments"
predict_data_path: "data/Train_Fractions.csv"
glycans_data_path: "data/Glycan-Structures-CFG611.txt"
proteins_data_path: "data/Protein-Sequence-Table.txt"
glycan_encoder_type: "dummy"
protein_encoder_type: "dummy"
binding_predictor_type: "mean"
glycan_type: "SMILES"
num_epochs: 1
batch_size: 32
learning_rate: 0.001
checkpoint_frequency: 2 # every nth epoch save the model weights (in this example every 2nd epoch so saves at epoch 2, 4, 6, ...)
train_final_model: False # if want to train and save the model on the best found params from cross val usinmg the entire training set.
log_predict: False # tranform our target to log(1+target) (log1p()) so that we dont train the model to predict all zeros (reverted on predictions output with expm1())
random_state: 42
# if not using kfold make sure to specify your val_split (the % of each glycan and protein class to split_mode combine into the validation set)
use_kfold: False # recomended to not use kfold if using split_mode AND as the splitting % vary greatly
split_mode: 'AND'
# optional
val_split: 0.5
k_folds: 3
device: "cpu"
model_specific_params: {}
hf_auth: False