batch_size: 32
binding_predictor_type: mean
checkpoint_frequency: 3
device: cpu
glycan_encoder_type: gnn
glycans_data_path: data/Glycan-Structures-CFG611.txt
hf_auth: false
k_folds: 3
learning_rate: 0.005
log_predict: true
model_specific_params: {}
num_epochs: 10
output_dir: experiments
predict_data_path: data/Train_Fractions.csv
protein_encoder_type: pt_gnn
proteins_data_path: data/Protein-Sequence-Table.txt
random_state: 42
split_mode: AND
eval_testset: False
testdata_path: 'data/Test_Fractions.csv'
train_final_model: false
use_kfold: false
val_split: 0.5
