# required
output_dir: "experiments"
predict_data_path: "data/Train_Fractions.csv"
glycans_data_path: "data/Glycan-Structures-CFG611.txt"
proteins_data_path: "data/Protein-Sequence-Table.txt"
glycan_encoder_type: "gnn"
protein_encoder_type: "biopy"
binding_predictor_type: "xgb"
num_epochs: 10
batch_size: 32
learning_rate: 0.005
checkpoint_frequency: 3 # every nth epoch save the model weights
train_final_model: False
log_predict: True # transform our target to log(1+target) so that we don't train the model to predict all zeros
random_state: 42
use_kfold: False 
split_mode: 'AND'
# optional
val_split: 0.5
k_folds: 3
device: "cpu"
model_specific_params:
  xgb_params:
    eta: 0.1
    max_depth: 8
    min_child_weight: 1
    subsample: 0.8
    colsample_bytree: 0.8
    n_estimators: 200
    tree_method: 'hist'
hf_auth: False